name: Links

on:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'
  push:
    branches: main
  pull_request:
    branches:
      - main

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332
        with:
          fail: true
